test:Add readme test and update readme
CeresDB/ceresdb-client-java pull request #20
Opened 2022-08-09 11:28 UTC by ZuLiangWang

# Which issue does this PR close?

# Rationale for this change
Update readme file and add runnable java code for readme.

# What changes are included in this PR?
Readme file details and test java code.

# Are there any user-facing changes?
all user used this client.

# How does this change test
Pass the CI

2022-08-09 11:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CeresDB/ceresdb-client-java?pullRequest=20) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CeresDB/ceresdb-client-java?pullRequest=20) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CeresDB/ceresdb-client-java?pullRequest=20) it.</sub>

2022-08-10 04:12 UTC, jiacai2050 requested changes

2022-08-10 04:12 UTC, jiacai2050 commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> +        final CeresDBxOptions opts = CeresDBxOptions.newBuilder("127.0.0.1", 8831) // CeresDB 默认配置端口号为 8831，不需要修改
It's better to add comments in English

2022-08-10 04:13 UTC, jiacai2050 commented
@ZuLiangWang Please sign CLA

2022-08-10 07:00 UTC, ZuLiangWang commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> +        final CeresDBxOptions opts = CeresDBxOptions.newBuilder("127.0.0.1", 8831) // CeresDB 默认配置端口号为 8831，不需要修改
fix

2022-08-10 07:36 UTC, jiacai2050 requested changes

2022-08-10 07:36 UTC, jiacai2050 commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> + * @date 2022/8/9 5:52 下午
- https://github.com/CeresDB/ceresdb-client-java/blob/4db4671c88c2d5675da7dcfb692d9be10101e3f9/ceresdb-http/src/main/java/com/ceresdb/http/HttpManagementClient.java#L53

I check other java files, only author is included, maybe we should keep the same format?

2022-08-10 07:38 UTC, jiacai2050 commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> +                // codes below organizes 3 lines data (3 timestamps) for the `cpu` and `mem` column, this will just transport once through network. CeresDB encourage practices like this, because the
typo: friendly

2022-08-10 07:42 UTC, jiacai2050 commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> +                // codes below organizes 3 lines data (3 timestamps) for the `cpu` and `mem` column, this will just transport once through network. CeresDB encourage practices like this, because the
reduce network overhead -> reduce network traffic

2022-08-11 02:43 UTC, ZuLiangWang commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> + * @date 2022/8/9 5:52 下午
fix, now the format is consistent with the original

2022-08-11 02:43 UTC, ZuLiangWang commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> +                // codes below organizes 3 lines data (3 timestamps) for the `cpu` and `mem` column, this will just transport once through network. CeresDB encourage practices like this, because the
fix

2022-08-11 02:43 UTC, ZuLiangWang commented on ceresdb-example/src/test/java/com/ceresdb/ReadmeTest.java
> +                // codes below organizes 3 lines data (3 timestamps) for the `cpu` and `mem` column, this will just transport once through network. CeresDB encourage practices like this, because the
fix

2022-08-12 06:12 UTC, jiacai2050 approved these changes

2022-08-12 06:13 UTC, merged